export const CHANGE_DIFFICULT = 'CHANGE_DIFFICULT';
export const CHANGE_TIME = 'CHANGE_TIME';
export const CHANGE_GAME_STATUS = 'CHANGE_GAME_STATUS';
export const CREATE_NEW_CARDS = 'CREATE_NEW_CARDS';
export const CHANGE_CARD_STATE = 'CHANGE_CARD_STATE';
